/*
Problem: 년, 월, 성별 별 상품 구매 회원 수 구하기 (Level 4)
URL: https://school.programmers.co.kr/learn/courses/30/lessons/131532
Concept: JOIN, GROUP BY, Date Functions, COUNT DISTINCT

[Approach]
1. JOIN USER_INFO and ONLINE_SALE on USER_ID.
2. Filter out NULL genders.
3. Group by YEAR, MONTH of SALES_DATE, and GENDER.
4. Count unique buyers using COUNT(DISTINCT S.USER_ID).
*/

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO AS I
INNER JOIN ONLINE_SALE AS S
ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER
ORDER BY YEAR ASC, MONTH ASC, I.GENDER ASC;